---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: world
  X: 193.4444
  "Y": 127.0522
  Z: -738.5201
  Yaw: 178.35891723632812
  Pitch: 7.9608612060546875
...
