---
Time changes: 0
Tell time: true
Tell time interval in minuts: 5
sb: 6
nether: 3
ender: 3
pvpvip: 1
world: 3
sb-tick: 6001
boss: 6
boss-tick: 12000
Test: 3
testt: 3
1o1: 3
Islands: 1
event: 3
ai: 3
Survival: 1
BuildBattle: 1
Shop: 3
Void Map: 3
pvp: 3
...
